//=========================================================
// inc/InitDevice.h: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================
#ifndef __INIT_DEVICE_H__
#define __INIT_DEVICE_H__

// USER CONSTANTS
// USER PROTOTYPES

// $[Mode Transition Prototypes]
extern void enter_DefaultMode_from_RESET(void);
// [Mode Transition Prototypes]$

// $[Config(Per-Module Mode)Transition Prototypes]
extern void HFXO_enter_DefaultMode_from_RESET(void);
extern void LFXO_enter_DefaultMode_from_RESET(void);
extern void CMU_enter_DefaultMode_from_RESET(void);
extern void ADC0_enter_DefaultMode_from_RESET(void);
extern void ACMP0_enter_DefaultMode_from_RESET(void);
extern void ACMP1_enter_DefaultMode_from_RESET(void);
extern void DAC0_enter_DefaultMode_from_RESET(void);
extern void BURTC_enter_DefaultMode_from_RESET(void);
extern void RTC_enter_DefaultMode_from_RESET(void);
extern void OPAMP0_enter_DefaultMode_from_RESET(void);
extern void OPAMP1_enter_DefaultMode_from_RESET(void);
extern void OPAMP2_enter_DefaultMode_from_RESET(void);
extern void USART0_enter_DefaultMode_from_RESET(void);
extern void USART1_enter_DefaultMode_from_RESET(void);
extern void USART2_enter_DefaultMode_from_RESET(void);
extern void LEUART0_enter_DefaultMode_from_RESET(void);
extern void LEUART1_enter_DefaultMode_from_RESET(void);
extern void VCMP_enter_DefaultMode_from_RESET(void);
extern void WDOG_enter_DefaultMode_from_RESET(void);
extern void I2C0_enter_DefaultMode_from_RESET(void);
extern void I2C1_enter_DefaultMode_from_RESET(void);
extern void TIMER0_enter_DefaultMode_from_RESET(void);
extern void TIMER1_enter_DefaultMode_from_RESET(void);
extern void TIMER2_enter_DefaultMode_from_RESET(void);
extern void TIMER3_enter_DefaultMode_from_RESET(void);
extern void LETIMER0_enter_DefaultMode_from_RESET(void);
extern void PCNT0_enter_DefaultMode_from_RESET(void);
extern void PCNT1_enter_DefaultMode_from_RESET(void);
extern void PCNT2_enter_DefaultMode_from_RESET(void);
extern void PRS_enter_DefaultMode_from_RESET(void);
extern void ETM_enter_DefaultMode_from_RESET(void);
extern void PORTIO_enter_DefaultMode_from_RESET(void);
// [Config(Per-Module Mode)Transition Prototypes]$

// $[User-defined pin name abstraction]

#define ADC0_CH7_PIN                (7)
#define ADC0_CH7_PORT               (gpioPortD)

#define BAT_CURRENT_SENSE_PIN       (8)
#define BAT_CURRENT_SENSE_PORT      (gpioPortD)

#define BAT_VOLTAGE_SENSE_PIN       (7)
#define BAT_VOLTAGE_SENSE_PORT      (gpioPortD)

#define BLE_INT_PIN                 (5)
#define BLE_INT_PORT                (gpioPortF)

#define BLE_RX_PIN                  (7)
#define BLE_RX_PORT                 (gpioPortC)

#define BLE_TX_PIN                  (6)
#define BLE_TX_PORT                 (gpioPortC)

#define BLE_WKUP_PIN                (15)
#define BLE_WKUP_PORT               (gpioPortA)

#define CD_PIN                      (8)
#define CD_PORT                     (gpioPortE)

#define CLK_FLASH_PIN               (12)
#define CLK_FLASH_PORT              (gpioPortE)

#define CS_FLASH_PIN                (13)
#define CS_FLASH_PORT               (gpioPortE)

#define GSM_PWR_KEY_PIN             (10)
#define GSM_PWR_KEY_PORT            (gpioPortC)

#define GSM_SLEEP_PIN               (9)
#define GSM_SLEEP_PORT              (gpioPortC)

#define GSM_VDD_SENS_PIN            (8)
#define GSM_VDD_SENS_PORT           (gpioPortC)

#define HFXO_N_PIN                  (14)
#define HFXO_N_PORT                 (gpioPortB)

#define HFXO_P_PIN                  (13)
#define HFXO_P_PORT                 (gpioPortB)

#define I2C0_SCL_PIN                (1)
#define I2C0_SCL_PORT               (gpioPortA)

#define I2C0_SDA_PIN                (0)
#define I2C0_SDA_PORT               (gpioPortA)

#define I2C_SCL_PIN                 (1)
#define I2C_SCL_PORT                (gpioPortA)

#define I2C_SDA_PIN                 (0)
#define I2C_SDA_PORT                (gpioPortA)

#define LEUART1_RX_PIN              (7)
#define LEUART1_RX_PORT             (gpioPortC)

#define LEUART1_TX_PIN              (6)
#define LEUART1_TX_PORT             (gpioPortC)

#define LFXO_N_PIN                  (8)
#define LFXO_N_PORT                 (gpioPortB)

#define LFXO_P_PIN                  (7)
#define LFXO_P_PORT                 (gpioPortB)

#define MISO_FLASH_PIN              (11)
#define MISO_FLASH_PORT             (gpioPortE)

#define MMA_INT1_PIN                (2)
#define MMA_INT1_PORT               (gpioPortA)

#define MMA_INT2_PIN                (3)
#define MMA_INT2_PORT               (gpioPortA)

#define MODEM_RX_PIN                (1)
#define MODEM_RX_PORT               (gpioPortD)

#define MODEM_TX_PIN                (0)
#define MODEM_TX_PORT               (gpioPortD)

#define MOSI_FLASH_PIN              (10)
#define MOSI_FLASH_PORT             (gpioPortE)

#define RTD_CS_PIN                  (5)
#define RTD_CS_PORT                 (gpioPortC)

#define RTD_DRDY_PIN                (14)
#define RTD_DRDY_PORT               (gpioPortE)

#define RTD_EN_PIN                  (11)
#define RTD_EN_PORT                 (gpioPortC)

#define RTD_MISO_PIN                (3)
#define RTD_MISO_PORT               (gpioPortC)

#define RTD_MOSI_PIN                (2)
#define RTD_MOSI_PORT               (gpioPortC)

#define RTD_SCK_PIN                 (4)
#define RTD_SCK_PORT                (gpioPortC)

#define STATUS_LED_PIN              (5)
#define STATUS_LED_PORT             (gpioPortD)

#define TAMPER_PIN                  (6)
#define TAMPER_PORT                 (gpioPortD)

#define TP1_PIN                     (5)
#define TP1_PORT                    (gpioPortA)

#define TP2_PIN                     (8)
#define TP2_PORT                    (gpioPortA)

#define TP3_PIN                     (9)
#define TP3_PORT                    (gpioPortE)

#define TP4_PIN                     (6)
#define TP4_PORT                    (gpioPortA)

#define UART_CTS_PIN                (3)
#define UART_CTS_PORT               (gpioPortD)

#define RING_PIN                    (2)
#define RING_PORT                   (gpioPortD)

#define UART_RTS_PIN                (4)
#define UART_RTS_PORT               (gpioPortD)

#define USART0_CLK_PIN              (12)
#define USART0_CLK_PORT             (gpioPortE)

#define USART0_CS_PIN               (13)
#define USART0_CS_PORT              (gpioPortE)

#define USART0_RX_PIN               (11)
#define USART0_RX_PORT              (gpioPortE)

#define USART0_TX_PIN               (10)
#define USART0_TX_PORT              (gpioPortE)

#define USART1_RX_PIN               (1)
#define USART1_RX_PORT              (gpioPortD)

#define USART1_TX_PIN               (0)
#define USART1_TX_PORT              (gpioPortD)

#define USART2_CLK_PIN              (4)
#define USART2_CLK_PORT             (gpioPortC)

#define USART2_CS_PIN               (5)
#define USART2_CS_PORT              (gpioPortC)

#define USART2_RX_PIN               (3)
#define USART2_RX_PORT              (gpioPortC)

#define USART2_TX_PIN               (2)
#define USART2_TX_PORT              (gpioPortC)

#define USB_DM_PIN                  (10)
#define USB_DM_PORT                 (gpioPortF)

#define USB_DP_PIN                  (11)
#define USB_DP_PORT                 (gpioPortF)

#define V_EXT_SEN_PIN               (4)
#define V_EXT_SEN_PORT              (gpioPortA)

#define V_FLASH_EN_PIN              (15)
#define V_FLASH_EN_PORT             (gpioPortE)

#define V_GNSS_EN_PIN               (12)
#define V_GNSS_EN_PORT              (gpioPortF)

#define V_GSM_EN_PIN                (9)
#define V_GSM_EN_PORT               (gpioPortA)

#define _1W_F_PIN                   (12)
#define _1W_F_PORT                  (gpioPortB)

#define _1_WIRE_EFM_PIN             (10)
#define _1_WIRE_EFM_PORT            (gpioPortA)

#define _5V_1WIRE_EN_PIN            (11)
#define _5V_1WIRE_EN_PORT           (gpioPortB)

#define _5V_EN_PIN                  (1)
#define _5V_EN_PORT                 (gpioPortC)

#define _5V_TR_EN_PIN               (0)
#define _5V_TR_EN_PORT              (gpioPortC)

// [User-defined pin name abstraction]$

#endif

